version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: vitaius-api
    environment:
      BRAND_NAME: "Vitaius"
      PRODUCT_NAME: "Vestra Forms"
      BLENDER_BIN: "blender"
      PROCESS_SCRIPT: "headless/process_cli.py"
    volumes:
      - ./:/app
    working_dir: /app
    command: uvicorn server.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: vitaius-worker
    environment:
      BLENDER_BIN: "blender"
      AXIS: "X"
      BASE_OFFSET_MM: "2.0"
      MOLD_PADDING_MM: "10.0"
      # You will override INPUT/outputs at run time
    volumes:
      - ./:/app
      - ./data:/data
    working_dir: /app
    entrypoint: ["/app/worker/entrypoint.sh"]
